backend:
  name: git-gateway
  branch: main # Cambia a "master" si tu rama principal se llama master

media_folder: "img"
public_folder: "/img"

collections:
  - name: "catalogo_inmuebles"
    label: "Catálogo Inmobiliario"
    files:
      - file: "propiedades.json"
        label: "Lista de Inmuebles"
        name: "lista_inmuebles"
        fields:
          - label: "Propiedades"
            name: "propiedades"
            widget: "list"
            summary: '{{fields.titulo}} - {{fields.precio}} €'
            fields:
              - { label: "ID Único", name: "id", widget: "number", value_type: "int" }
              - { label: "Título de la Propiedad", name: "titulo", widget: "string" }
              - { label: "Precio (€)", name: "precio", widget: "number", value_type: "int" }
              - { label: "Municipio", name: "municipio", widget: "string" }
              - { label: "Ubicación Completa", name: "ubicacion", widget: "string" }
              - { label: "Tipo", name: "tipo", widget: "select", options: ["venta", "alquiler"] }
              - { label: "Habitaciones", name: "habitaciones", widget: "number", default: 1 }
              - { label: "Baños", name: "banos", widget: "number", default: 1 }
              - { label: "Metros Cuadrados (m²)", name: "metros_cuadrados", widget: "number", default: 0 }
              - { label: "Garaje", name: "garaje", widget: "string", required: false }
              - { label: "Trastero", name: "trastero", widget: "string", required: false }
              - { label: "Etiqueta Destacada", name: "etiqueta", widget: "string", required: false }
              - { label: "Imagen Principal", name: "imagen", widget: "image" }
              - label: "Galería de Imágenes"
                name: "galeria"
                widget: "list"
                required: false
                field: { label: "Imagen", name: "foto", widget: "image" }
              - label: "Coordenadas Mapa"
                name: "coordenadas"
                widget: "object"
                fields:
                  - { label: "Latitud", name: "latitud", widget: "number", value_type: "float" }
                  - { label: "Longitud", name: "longitud", widget: "number", value_type: "float" }
              - { label: "Descripción", name: "descripcion", widget: "text" }